FROM ubuntu

WORKDIR /app

# Install system dependencies
RUN apt-get update && \
    apt-get install -y python3 python3-pip python3-venv

# Create a virtual environment
RUN python3 -m venv venv

# Activate the virtual environment
ENV PATH="/app/venv/bin:$PATH"

# Copy requirements and install packages
COPY requirements.txt /app/
RUN pip install -r requirements.txt

# Copy your application code (edit as required)
COPY mycar /app/

# Set the entrypoint
ENTRYPOINT ["python3"]
CMD ["manage.py", "runserver", "0.0.0.0:8000"]




