apiVersion: v1
kind: Service
metadata:
  name: mycar-service
spec:
  type: NodePort
  selector:
    app: mycar-python-app           #this is taken from label under templates of deploy.yml file 
  ports:
    - port: 80
      # By default and for convenience, the `targetPort` is set to
      # the same value as the `port` field.
      # but here we will set it as where app is running or container port as mentioned on dockerfile
      targetPort: 8000
      # Optional field
      # By default and for convenience, the Kubernetes control plane
      # will allocate a port from a range (default: 30000-32767)
      nodePort: 30000

